tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "wallix/awless"
cask "java"
brew "amazon-ecs-cli"
brew "aria2"
brew "awscli"
brew "bazel"
brew "byobu"
brew "elinks"
brew "emacs"
brew "exa"
brew "go"
brew "htop"
brew "httpie"
brew "iftop"
brew "ipcalc"
brew "jq"
brew "less"
brew "links"
brew "lynx"
brew "mas"
brew "most"
brew "netcat"
brew "nethogs"
brew "nmap"
brew "node"
brew "rsync"
brew "screen"
brew "siege"
brew "socat"
brew "vim"
brew "w3m"
brew "wallix/awless/awless"
cask "android-studio"
cask "appcode"
cask "arduino"
cask "caffeine"
cask "clion"
cask "dash"
cask "datagrip"
cask "discord"
cask "dropbox"
cask "gogland"
cask "google-backup-and-sync"
cask "google-chrome"
cask "hyper"
cask "intellij-idea"
cask "iterm2"
cask "paw"
cask "postman"
cask "pycharm"
cask "rider"
cask "slack"
cask "spotify"
cask "unity"
cask "webstorm"
mas "BetterSnapTool", id: 417375580
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Server", id: 883878097
mas "Xcode", id: 497799835
